# !/bin/bash

python main.py --experiment_type error --device cuda:1 --network resnet --depth 20 --dataset cifar100 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 56 --dataset cifar100 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:1 --network densenet --depth 121 --dataset cifar100 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:1 --network pyramidnet --depth 164 --dataset cifar100 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 20 --dataset cifar100 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 56 --dataset cifar100 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network densenet --depth 121 --dataset cifar100 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network pyramidnet --depth 164 --dataset cifar100 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 20 --dataset cifar100 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 56 --dataset cifar100 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network densenet --depth 121 --dataset cifar100 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network pyramidnet --depth 164 --dataset cifar100 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 20 --dataset cifar100 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 56 --dataset cifar100 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network densenet --depth 121 --dataset cifar100 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network pyramidnet --depth 164 --dataset cifar100 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 20 --dataset cifar100 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network resnet --depth 56 --dataset cifar100 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network densenet --depth 121 --dataset cifar100 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:1 --network pyramidnet --depth 164 --dataset cifar100 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300

python main.py --experiment_type error --device cuda:0 --network resnet --depth 20 --dataset cifar10 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 56 --dataset cifar10 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:0 --network densenet --depth 121 --dataset cifar10 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:0 --network pyramidnet --depth 164 --dataset cifar10 --optimizer DNGD --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 0.2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 20 --dataset cifar10 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 56 --dataset cifar10 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network densenet --depth 121 --dataset cifar10 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network pyramidnet --depth 164 --dataset cifar10 --optimizer SGD_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 20 --dataset cifar10 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 56 --dataset cifar10 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network densenet --depth 121 --dataset cifar10 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network pyramidnet --depth 164 --dataset cifar10 --optimizer Adam_ --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 20 --dataset cifar10 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 56 --dataset cifar10 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network densenet --depth 121 --dataset cifar10 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network pyramidnet --depth 164 --dataset cifar10 --optimizer kfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 20 --dataset cifar10 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network resnet --depth 56 --dataset cifar10 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network densenet --depth 121 --dataset cifar10 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300
python main.py --experiment_type error --device cuda:0 --network pyramidnet --depth 164 --dataset cifar10 --optimizer ekfac --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 5 --TScal 5 --TInv 5 --epoch 300


python main.py --experiment_type error --network mlp --depth 3 --dataset mnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type error --network mlp --depth 3 --dataset mnist --optimizer SGD_ --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 100
python main.py --experiment_type error --network mlp --depth 3 --dataset mnist --optimizer Adam_ --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --epoch 100
python main.py --experiment_type error --network mlp --depth 3 --dataset mnist --optimizer kfac --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 5 --TScal 5 --TInv 5 --epoch 100
python main.py --experiment_type error --network mlp --depth 3 --dataset mnist --optimizer ekfac --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 5 --TScal 5 --TInv 5 --epoch 100

python main.py --experiment_type error --network mlp --depth 3 --dataset fashionmnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type error --network mlp --depth 3 --dataset fashionmnist --optimizer SGD_ --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 100
python main.py --experiment_type error --network mlp --depth 3 --dataset fashionmnist --optimizer Adam_ --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --epoch 100
python main.py --experiment_type error --network mlp --depth 3 --dataset fashionmnist --optimizer kfac --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 5 --TScal 5 --TInv 5 --epoch 100
python main.py --experiment_type error --network mlp --depth 3 --dataset fashionmnist --optimizer ekfac --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 5 --TScal 5 --TInv 5 --epoch 100

python main.py --experiment_type damping --network mlp --depth 3 --dataset mnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset mnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset mnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset mnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset mnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset mnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset mnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 100

python main.py --experiment_type damping --network mlp --depth 3 --dataset fashionmnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset fashionmnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset fashionmnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset fashionmnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset fashionmnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset fashionmnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 100
python main.py --experiment_type damping --network mlp --depth 3 --dataset fashionmnist --optimizer dngd --learning_rate 0.01 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 100

python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar10 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300


python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 20 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 28 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network resnet --depth 56 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network wrn --depth 58 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network pyramidnet --depth 164 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 10.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1.0 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-1 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 5e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-2 --TCov 1 --TScal 1 --TInv 1 --epoch 300
python main.py --experiment_type damping --network densenet --depth 121 --widen_factor 6 --dataset cifar100 --optimizer dngd --learning_rate 0.1 --batch_size 128 --weight_decay 5e-4 --momentum 0.9 --damping 1e-3 --TCov 1 --TScal 1 --TInv 1 --epoch 300